[package]
name = "calc"
version = "0.1.0"
authors = ["Bryce Kabat <brycekabat@onyxazryn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
